### ISSUE TITLE
Host on Azure & related setup

### ISSUE THREAD

**Issue by RaenonX** [RaenonX-DL/dragalia-site-front#67]
- [x] **Front** - Azure pipeline migrate from GH Actions
  - [x] Use `npm ci`
  - [x] `npm run lint` and `npm run lint:css`
  - [x] `npm run test:ci-jest`
  - [x] Send coverage to both Azure and Codacy
  - [x] `npm run test:ci-e2e` after build, before sending artifact
    - [x] Upload `.cypress/screenshots` and `.cypress/videos` if this fails
  - [x] Build and run cypress test with `NODE_ENV=production`
  - [x] Cypress test with `PORT=3000`
```
env:
  # Need to use real backends for cypress testings
  NEXT_PUBLIC_API_ROOT: https://dl-back.raenonx.cc
  NEXT_PUBLIC_RESOURCE_ROOT: https://raw.githubusercontent.com/RaenonX-DL/dragalia-site-resources/main
  NEXT_PUBLIC_DEPOT_ROOT: https://raw.githubusercontent.com/RaenonX-DL/dragalia-data-depot/main
  NEXTAUTH_URL: http://localhost:3000
  CI: true
```
- [x] **Back** - Deploy VM
  - [x] Change `package.json` like 6c2b1d0
- [x] **Back** - Check Azure DevOps
  - [x] Disable GH Actions
  - [x] CI
  - [x] CD
- [x] **Back** - Check APM working
- [x] **Back** - NS link to VM
  - [x] Remove DigitalOcean instances
- [x] APM Dashboards
  - [x] System performance (CPU / RAM / Disk / Net)
  - [x] NGINX (Connections / Requests)
- [x] APM Tags
  - [x] NGINX
- [x] Azure dashboard
  - [x] CPU / RAM
  - [x] Disk
- [x] Update status badges
  - [x] Status board
  - [x] Front README
  - [x] Back README
- [x] **Front/Back** Merge `azure` to `main`
- [x] **Front/Back** Restore GH Actions
  - [x] Remove CI/CD
  - [x] Enable security scan
